"""add ingestion model

Revision ID: a2287198a475
Revises: 1cdb4384cfd9
Create Date: 2026-06-19 11:51:47.659532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2287198a475'
down_revision: Union[str, Sequence[str], None] = '1cdb4384cfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestions', sa.Column('json_url', sa.Text(), nullable=True))
    op.add_column('ingestions', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('ingestions', sa.Column('failed_at_stage', sa.String(length=50), nullable=True))
    op.add_column('ingestions', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('ingestions', 'file_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ingestions', 'file_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('ingestions_user_id_fkey'), 'ingestions', type_='foreignkey')
    op.create_foreign_key(None, 'ingestions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ingestions', 'tokens_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestions', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingestions', type_='foreignkey')
    op.create_foreign_key(op.f('ingestions_user_id_fkey'), 'ingestions', 'users', ['user_id'], ['id'])
    op.alter_column('ingestions', 'file_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ingestions', 'file_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('ingestions', 'error_message')
    op.drop_column('ingestions', 'failed_at_stage')
    op.drop_column('ingestions', 'chunk_count')
    op.drop_column('ingestions', 'json_url')
    # ### end Alembic commands ###
